version: "3"

services:
  app:
    image: node:10.15-stretch-slim
    volumes:
      - .:/app
      - yarn-cache:/usr/local/share/.cache/yarn
    ports:
      - 1234:1234
      - 1235:1235
    tty: true
    working_dir: /app

volumes:
  yarn-cache:
